- hosts: nobelium

  vars:
    server_name: "{{ ansible_facts['hostname']}}"
    str: This is server {{ server_name }}!
    root_dir: '/usr/share/nginx/html'

  tasks:
    - name: Copy index.html
      ansible.builtin.template:
        src: templates/index.html.j2
        dest: '{{root_dir}}/index.html'
        become: yes
