- hosts: webservers

  tasks:
    - name: Set authorized key took from file
      authorized_key:
        user: user
        state: present
        key: "{{ lookup('file', '/home/user/.ssh/id_rsa.pub') }}"

    - name: remove git
      ansible.builtin.apt:
        name: git
        state: absent
        update_cache: yes
      become: yes # <---
