- hosts: webservers

  tasks:
    - name: Set authorized key took from file
      authorized_key:
        user: user
        state: present
        key: "{{ lookup('file', '/home/user/.ssh/id_rsa.pub') }}"

    - name: install git
      ansible.builtin.apt:
        name: git
        state: present
      become: yes # <---
      tags: git

    - name: update cache
      ansible.builtin.apt:
        update_cache: yes
      become: yes # <---
      tags: cache
